name: Keep-Alive Render API

on:
  schedule:
    - cron: '*/12 15-23 * * *'
    - cron: '*/12 0-3 * * *'
  workflow_dispatch: # Permite probarlo manualmente con un botón

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer Ping a Render
        env:
          RENDER_API_URL: ${{ secrets.RENDER_API_URL }}
        run: |
          echo "Enviando ping a Render..."
          curl -s -f "$RENDER_API_URL" || exit 1
          echo "Ping completado con éxito."
